export const REQUEST_BOOKMARKS = 'REQUEST_BOOKMARKS';
export const RECEIVE_BOOKMARKS = 'RECEIVE_BOOKMARKS';

export const REQUEST_APP_CONFIG = 'REQUEST_APP_CONFIG';
export const RECEIVE_APP_CONFIG = 'RECEIVE_APP_CONFIG';

export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const QUIT_SEARCH_PAGE = 'QUIT_SEARCH_PAGE';

export const REQUEST_OTHER_SEARCH = 'REQUEST_OTHER_SEARCH';
export const RECEIVE_OTHER_SEARCH = 'RECEIVE_OTHER_SEARCH';

export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE';
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';

export const REQUEST_CATALOG = 'REQUEST_CATALOG';
export const RECEIVE_CATALOG = 'RECEIVE_CATALOG';
export const CLEAR_CATALOG = 'CLEAR_CATALOG';

export const REQUEST_DETAIL = 'REQUEST_DETAIL';
export const RECEIVE_DETAIL = 'RECEIVE_DETAIL';
export const CLEAR_DETAIL = 'CLEAR_DETAIL';

export const REQUEST_RANKINGS = 'REQUEST_RANKINGS';
export const RECEIVE_RANKINGS = 'RECEIVE_RANKINGS';

export const REQUEST_RANKING_DETAIL = 'REQUEST_RANKING_DETAIL';
export const RECEIVE_RANKING_DETAIL = 'RECEIVE_RANKING_DETAIL';
export const CLEAR_RANKING_DETAIL = 'CLEAR_RANKING_DETAIL';

export const REQUEST_HOT_REC = 'REQUEST_HOT_REC';
export const RECEIVE_HOT_REC = 'RECEIVE_HOT_REC';

export const REQUEST_HOT_SIMILAR = 'REQUEST_HOT_SIMILAR';
export const RECEIVE_HOT_SIMILAR = 'RECEIVE_HOT_SIMILAR';

export const REQUEST_EDITOR_REC = 'REQUEST_EDITOR_REC';
export const RECEIVE_EDITOR_REC = 'RECEIVE_EDITOR_REC';

export const REQUEST_BEST_END = 'REQUEST_BEST_END';
export const RECEIVE_BEST_END = 'RECEIVE_BEST_END';

export const REQUEST_SPREAD = 'REQUEST_SPREAD';
export const RECEIVE_SPREAD = 'RECEIVE_SPREAD';

export const REQUEST_CATEGORY = 'REQUEST_CATEGORY';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';

export const REQUEST_CATEGORY_DETAIL = 'REQUEST_CATEGORY_DETAIL';
export const RECEIVE_CATEGORY_DETAIL = 'RECEIVE_CATEGORY_DETAIL';
export const CLEAR_BOOK_CACHE = 'CLEAR_BOOK_CACHE';

export const REQUEST_GUESS_YOU_LIKE = 'REQUEST_GUESS_YOU_LIKE';
export const RECEIVE_GUESS_YOU_LIKE = 'RECEIVE_GUESS_YOU_LIKE';

export const REQUEST_HOT_SEARCH = 'REQUEST_HOT_SEARCH';
export const RECEIVE_HOT_SEARCH = 'RECEIVE_HOT_SEARCH';

export const REQUEST_NOTIFICATION = 'REQUEST_NOTIFICATION';
export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';

